"""add risk_justification to consultation_analysis

Revision ID: 04a673f1568a
Revises: 70b3b2dd1b67
Create Date: 2026-04-26 23:52:46.233473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a673f1568a'
down_revision: Union[str, Sequence[str], None] = '70b3b2dd1b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_analysis', sa.Column('risk_justification', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_analysis', 'risk_justification')
    # ### end Alembic commands ###
