"""add referral_explanation to consultation_decisions

Revision ID: 44c347fd6a96
Revises: e2e102024bb8
Create Date: 2026-04-26 19:20:58.872857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c347fd6a96'
down_revision: Union[str, Sequence[str], None] = 'e2e102024bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_decisions', sa.Column('referral_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_decisions', 'referral_explanation')
    # ### end Alembic commands ###
