"""add red_flags and key_negatives to consultation_analysis

Revision ID: 70b3b2dd1b67
Revises: 44c347fd6a96
Create Date: 2026-04-26 22:34:58.691692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b3b2dd1b67'
down_revision: Union[str, Sequence[str], None] = '44c347fd6a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_analysis', sa.Column('red_flags', sa.TEXT(), nullable=True))
    op.add_column('consultation_analysis', sa.Column('key_negatives', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_analysis', 'key_negatives')
    op.drop_column('consultation_analysis', 'red_flags')
    # ### end Alembic commands ###
