"""add referral_options to consultation_decisions

Revision ID: e2e102024bb8
Revises: b3f892ac1d40
Create Date: 2026-04-26 18:23:39.000805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e102024bb8'
down_revision: Union[str, Sequence[str], None] = 'b3f892ac1d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_decisions', sa.Column('referral_options', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_decisions', 'referral_options')
    # ### end Alembic commands ###
