from enum import Enum

class USSDState(str, Enum):

    MAIN_MENU = "MAIN_MENU"

    REGISTER_FIRST_NAME = "REGISTER_FIRST_NAME"
    REGISTER_LAST_NAME = "REGISTER_LAST_NAME"
    REGISTER_EMAIL = "REGISTER_EMAIL"
    REGISTER_PIN = "REGISTER_PIN"
    REGISTER_CONFIRM_PIN = "REGISTER_CONFIRM_PIN"

    END = "END"

class PersonalInfoMenu(str, Enum):
    MENU = "PERSONAL_INFO_MENU"

class MedicalInfoMenu(str, Enum):
    MENU = "MEDICAL_INFO_MENU"

class USSDPersonalInfo(str, Enum):

    MAIN_MENU = "PERSONAL_INFO"

    VERIFY_PIN = "PIN"
    COMPLETE_AGE = "REGISTER_AGE"
    COMPLETE_GENDER = "REGISTER_GENDER"
    COMPLETE_NATIONALITY = "REGISTER_NATIONALITY"
    COMPLETE_COUNTRY_OF_RESIDENCE = "REGISTER_COUNTRY_OF_RESIDENCE"
    COMPLETE_CITY_OF_RESIDENCE = "REGISTER_CITY_OF_RESIDENCE"
    COMPLETE_ADDRESS = "REGISTER_ADDRESS"
    COMPLETE_NEXT_KIN = "REGISTER_NEXT_KIN"
    COMPLETE_NEXT_KIN_RELATIONSHIP = "PATIENT_NEXT_KIN_RELATIONSHIP"
    COMPLETE_NEXT_KIN_PHONE_NUMBER = "PATIENT_NEXT_KIN_PHONE_NUMBER"
    COMPLETE_PREFERRED_LANGUAGE = "PATIENT_PREFERRED_LANGUAGE"

    END = "END"

class USSDMedicalInfo(str, Enum):
    MAIN_MENU = "MEDICAL_INFO"

    VERIFY_PIN = "PIN"
    BLOOD_TYPE = "ADD_BLOOD_TYPE"
    ALLERGIES = "ADD_ALLERGIES"
    CHRONIC_ILLNESS = "CHRONIC_ILLNESS"
    RECENT_VACCINATION = "RECENT_VACCINATIONS"

    END = "END"

class ViewInfo(str, Enum):
    MAIN_MENU = "VIEW_INFO"

    VERIFY_PIN = "PIN"
    MEDICAL_INFO = "MEDICAL_INFO"

class ViewPersonalInfo(str, Enum):
    MAIN_MENU = "VIEW_INFO"

    VERIFY_PIN = "PIN"
    PERSONAL_INFO = "PERSONAL_INFO"

class ConsultationHistory(str, Enum):
    VERIFY_PIN = "CH_VERIFY_PIN"
    LIST       = "CH_LIST"
    DETAIL_MENU = "CH_DETAIL_MENU"
    SUMMARY    = "CH_SUMMARY"
    ANALYSIS   = "CH_ANALYSIS"
    DECISION   = "CH_DECISION"

# kept for backward compatibility — no longer used in engine dispatch
class ViewConsultation(str, Enum):
    MAIN_MENU  = "CONSULTATION"
    VERIFY_PIN = "PIN"
